CLOS DATA
SET SAFETY ON
SELECT 0
USE ordhea
ZAP
SELECT 0
USE ordrow
ZAP
SELECT 0
USE arrhea
ZAP
SELECT 0
USE arrrow
ZAP
SELECT 0
USE invhea
ZAP
SELECT 0
USE invrow
ZAP
SELECT 0
USE paytab
ZAP
SELECT 0
USE platab
ZAP
SELECT 0
USE quogrp
ZAP
SELECT 0
USE quohea
ZAP
SELECT 0
USE quorow
ZAP
SELECT 0
USE sertab
ZAP
SELECT 0
USE trahea
ZAP
SELECT 0
USE trarow
ZAP
