VERSION 5.00
Begin VB.Form frmbot 
   BackColor       =   &H00C0C0FF&
   ClientHeight    =   7140
   ClientLeft      =   2355
   ClientTop       =   1455
   ClientWidth     =   9465
   LinkTopic       =   "Form1"
   ScaleHeight     =   7140
   ScaleWidth      =   9465
End
Attribute VB_Name = "frmbot"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = True
Attribute VB_Exposed = False
